"""
This file is generated by generator/run.py with chrome-devtools-protocol.


https://chromedevtools.github.io/devtools-protocol/tot/LayerTree/

***************************************************
                    Events
***************************************************
"""
from __future__ import annotations

from cdpkit.common import CDPEvent
from cdpkit.protocol._types import (
    DOM,
    LayerTree,
)


class LayerPainted(CDPEvent):

    layerId: LayerTree.LayerId  # deprecated
    clip: DOM.Rect  # deprecated


class LayerTreeDidChange(CDPEvent):

    layers: LayerTree.Layer | None = None  # deprecated
