"""
This file is generated by generator/run.py with chrome-devtools-protocol.


https://chromedevtools.github.io/devtools-protocol/tot/LayerTree/

***************************************************
                    Events
***************************************************
"""
from __future__ import annotations

from cdpkit.protocol._types import (
    DOM,
    LayerTree,
)
from cdpkit.protocol.base import CDPEvent


class LayerPainted(CDPEvent):

    layerId: LayerTree.LayerId  # deprecated
    clip: DOM.Rect  # deprecated


class LayerTreeDidChange(CDPEvent):

    layers: list[LayerTree.Layer] | None = None  # deprecated
