"""
This file is generated by generator/run.py with chrome-devtools-protocol.

This domain is deprecated.
https://chromedevtools.github.io/devtools-protocol/tot/Schema/

***************************************************
                    Events
***************************************************
"""
from __future__ import annotations
