"""
This file is generated by generator/run.py with chrome-devtools-protocol.

This domain is deprecated.
https://chromedevtools.github.io/devtools-protocol/tot/Schema/

***************************************************
                    Methods
***************************************************
"""
from __future__ import annotations

from cdpkit.common import CDPMethod, OutputModel
from cdpkit.protocol._types import (
    Schema,
)


class GetDomainsOutput(OutputModel):

    domains: list[Schema.Domain]  # deprecated


class GetDomains(CDPMethod[GetDomainsOutput]):  # deprecated
    """ Returns supported domains. """

    INPUT_VALIDATOR = None
    OUTPUT_VALIDATOR = GetDomainsOutput
