"""
This file is generated by generator/run.py with chrome-devtools-protocol.

This domain is deprecated.
https://chromedevtools.github.io/devtools-protocol/tot/Schema/

***************************************************
                    Types
***************************************************
"""
from __future__ import annotations

from cdpkit.protocol._types import (
    SchemaDomain,
)

Domain = SchemaDomain
