"""
This file is generated by generator/run.py with chrome-devtools-protocol.


https://chromedevtools.github.io/devtools-protocol/tot/Inspector/

***************************************************
                    Methods
***************************************************
"""
from __future__ import annotations

from cdpkit.protocol.base import CDPMethod


class Disable(CDPMethod[None]):  # deprecated
    """ Disables inspector domain notifications. """

    INPUT_VALIDATOR = None
    OUTPUT_VALIDATOR = None


class Enable(CDPMethod[None]):  # deprecated
    """ Enables inspector domain notifications. """

    INPUT_VALIDATOR = None
    OUTPUT_VALIDATOR = None
