"""
This file is generated by generator/run.py with chrome-devtools-protocol.


https://chromedevtools.github.io/devtools-protocol/tot/Input/

***************************************************
                    Events
***************************************************
"""
from __future__ import annotations

from cdpkit.common import CDPEvent
from cdpkit.protocol._types import (
    Input,
)


class DragIntercepted(CDPEvent):
    """ Emitted only when `Input.setInterceptDrags` is enabled. Use this data with `Input.dispatchDragEvent` to
    restore normal drag and drop behavior. """

    data: Input.DragData
