"""
This file is generated by generator/run.py with chrome-devtools-protocol.


https://chromedevtools.github.io/devtools-protocol/tot/DeviceAccess/

***************************************************
                    Events
***************************************************
"""
from __future__ import annotations

from cdpkit.common import CDPEvent
from cdpkit.protocol._types import (
    DeviceAccess,
)


class DeviceRequestPrompted(CDPEvent):
    """ A device request opened a user prompt to select a device. Respond with the
    selectPrompt or cancelPrompt command. """

    id: DeviceAccess.RequestId
    devices: DeviceAccess.PromptDevice
