"""
This file is generated by generator/run.py with chrome-devtools-protocol.

Defines commands and events for browser extensions.
https://chromedevtools.github.io/devtools-protocol/tot/Extensions/

***************************************************
                    Events
***************************************************
"""
from __future__ import annotations
