"""
This file is generated by generator/run.py with chrome-devtools-protocol.


https://chromedevtools.github.io/devtools-protocol/tot/Performance/

***************************************************
                    Events
***************************************************
"""
from __future__ import annotations

from cdpkit.common import CDPEvent
from cdpkit.protocol._types import (
    Performance,
)


class Metrics(CDPEvent):
    """ Current values of the metrics. """

    metrics: list[Performance.Metric]  # deprecated
    title: str  # deprecated
