"""
This file is generated by generator/run.py with chrome-devtools-protocol.


https://chromedevtools.github.io/devtools-protocol/tot/DeviceOrientation/

***************************************************
                    Types
***************************************************
"""
from __future__ import annotations
