"""
This file is generated by generator/run.py with chrome-devtools-protocol.

This domain allows configuring virtual Bluetooth devices to test
the web-bluetooth API.
https://chromedevtools.github.io/devtools-protocol/tot/BluetoothEmulation/

***************************************************
                    Events
***************************************************
"""
from __future__ import annotations

from cdpkit.protocol._types import (
    BluetoothEmulation,
)
from cdpkit.protocol.base import CDPEvent


class GattOperationReceived(CDPEvent):
    """ Event for when a GATT operation of |type| to the peripheral with |address|
    happened. """

    address: str
    type: BluetoothEmulation.GATTOperationType
