"""
This file is generated by generator/run.py with chrome-devtools-protocol.

This domain allows configuring virtual Bluetooth devices to test
the web-bluetooth API.
https://chromedevtools.github.io/devtools-protocol/tot/BluetoothEmulation/

***************************************************
                    Types
***************************************************
"""
from __future__ import annotations

from cdpkit.protocol._types import (
    BluetoothEmulationCentralState,
    BluetoothEmulationCharacteristicProperties,
    BluetoothEmulationGATTOperationType,
    BluetoothEmulationManufacturerData,
    BluetoothEmulationScanEntry,
    BluetoothEmulationScanRecord,
)

CentralState = BluetoothEmulationCentralState
GATTOperationType = BluetoothEmulationGATTOperationType
ManufacturerData = BluetoothEmulationManufacturerData
ScanRecord = BluetoothEmulationScanRecord
ScanEntry = BluetoothEmulationScanEntry
CharacteristicProperties = BluetoothEmulationCharacteristicProperties
