"""
This file is generated by generator/run.py with chrome-devtools-protocol.

Audits domain allows investigation of page violations and possible improvements.
https://chromedevtools.github.io/devtools-protocol/tot/Audits/

***************************************************
                    Events
***************************************************
"""
from __future__ import annotations

from cdpkit.common import CDPEvent
from cdpkit.protocol._types import (
    Audits,
)


class IssueAdded(CDPEvent):

    issue: Audits.InspectorIssue
