"""
This file is generated by generator/run.py based on the Chrome DevTools Protocol.

This domain is deprecated - use Runtime or Log instead.
https://chromedevtools.github.io/devtools-protocol/tot/Console/

***************************************************
                    Methods
***************************************************
"""
from __future__ import annotations

from cdpkit.protocol.base import CDPMethod


class ClearMessages(CDPMethod[None]):  # deprecated
    """ Does nothing. """

    INPUT_VALIDATOR = None
    OUTPUT_VALIDATOR = None


class Disable(CDPMethod[None]):  # deprecated
    """ Disables console domain, prevents further console messages from being reported to the client. """

    INPUT_VALIDATOR = None
    OUTPUT_VALIDATOR = None


class Enable(CDPMethod[None]):  # deprecated
    """ Enables console domain, sends the messages collected so far to the client by means of the
    `messageAdded` notification. """

    INPUT_VALIDATOR = None
    OUTPUT_VALIDATOR = None
